language: go


matrix:
  include:
    - go: 1.7.x
    - go: 1.8.x
    - go: 1.9.x
    - go: 1.10.x
    - go: 1.11.x
    - go: 1.x
      env: LATEST=true

install:
  - # Skip

script:
  - if [[ "$LATEST" = true ]]; then go vet .; fi
  - go test -v ./...

